# Dependencies
markdown:            redcarpet
extensions:    ["with_toc_data", "tables"]
highlighter:         pygments
exclude:	    []

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:              RoastPotatoes 
tagline:             ''
description:         'This is a blog about mechanical keyboards and artisan keycaps'
url:                 https://roastpotatoes.github.io 
baseurl:             /
paginate:            3

# About/contact
author:
  name:            T Rad  
  url:              
  email:             

# Custom vars
version:             1.0.0
ctrlalt: <span class="ctrlalt"><a href="https://ctrlalt.io/">[CTRL]ALT</a></span>

gems:
- jekyll-sitemap
- jekyll-redirect-from
