# Dependencies
markdown:            redcarpet
highlighter:         pygments
exclude:	    []

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:              RoastPotatoes 
tagline:             ''
description:         'This is where I am hoping to write about keyboards and linux.'
url:                 roastpotatoes.github.io 
baseurl:             /
paginate:            5

# About/contact
author:
  name:            T Rad  
  url:              
  email:             

# Custom vars
version:             1.0.0

prose:
	rooturl: "_posts
siteurl: "https://roastpotatoes.github.io"
    metadata:
      _posts/:
	- name: "layout"
	      field:
		element: "hidden"
		value: "post"
	- name: "title"
              field:
		element: "text"
                label: "Title"
               value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "tmk"
              value: "tmk"
            - name: "ErgoDox"
              value: "ErgoDox"
            - name: "News"
              value: "News"
	    - name: "How-to"
	    value: "How-to"
_drafts:
	- name: "layout"
	      field:
		element: "hidden"
		value: "post"
	- name: "title"
              field:
		element: "text"
                label: "Title"
                 value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "tmk"
              value: "tmk"
            - name: "ErgoDox"
              value: "ErgoDox"
            - name: "News"
              value: "News"
	    - name: "How-to"
	    value: "How-to"
