# Dependencies
markdown:            kramdown
extensions:    ["with_toc_data", "tables"]
highlighter:         rouge
exclude:	    []

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:              RoastPotatoes
tagline:             ''
description:         'This is a blog about mechanical keyboards and artisan keycaps'
url:                 http://blog.roastpotatoes.co
baseurl:             /

# About/contact
author:
  name:            T Rad
  url:
  email:

# Custom vars
version:             1.2.0
ctrlalt: <span class="ctrlalt"><a href="https://ctrlalt.io/">[CTRL]ALT</a></span>

paginate_path: "page:num"

plugins:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-paginate


paginate:            3

